### ISSUE TITLE
Not able to get a useful response

### ISSUE THREAD

**Issue by loryanstrant** [joselcaguilar/azure-openai-ha#16]
I'm wondering if I've missed something with my setup. Trying the example in the LinkedIn article, I get this:
![image](https://user-images.githubusercontent.com/51473494/235264786-b47991c9-94fe-447c-9537-7b6f59229873.png)

I only have a single model configured:
![image](https://user-images.githubusercontent.com/51473494/235264845-0bd0dff1-2650-4394-9999-1c216620cd71.png)

In HA I only have a single model configured as well:
![image](https://user-images.githubusercontent.com/51473494/235265076-02d701d4-4a0b-4e63-b797-85a5551884a3.png)

If I ask about a device:
![image](https://user-images.githubusercontent.com/51473494/235265133-df5072f7-359a-47a6-9541-d0f2d31cf6dc.png)

However, it does look like it's at least getting some data from HA by the fact it was able to show the friendly name of the device:
![image](https://user-images.githubusercontent.com/51473494/235265276-a65eb5b8-b578-43da-a334-b7bfec96bef2.png)

Is there some way I need to configure this to use the Prompt Template? Is there something I need to do in HA or Azure to get it to return information?

**Comment by loryanstrant** [comment]
I am able to get it to tell me about what's in an area though:
![image](https://user-images.githubusercontent.com/51473494/235266035-4ce819ec-fad8-4c9b-b521-9eb9653ec5e0.png)

**Comment by joselcaguilar** [comment]
That's normal @loryanstrant, you need to provide a different `Prompt Template` because Azure OpenAI doesn't have your info by default unless you provide it, for more info: https://www.home-assistant.io/docs/configuration/templating

For example, you can provide the owner name and current time and date like this:
```yaml
Name of user: {{person}}
Source of message to IO: text message

The Current time and date is: {{now().year}}-{{now().month}}-{{now().day}}
The current day of the week is {{now().strftime('%A') }}
```
