### ISSUE TITLE
broken 3.0 branch: 404 response

### ISSUE THREAD

**Issue by temporaer** [joselcaguilar/azure-openai-ha#92]
Thanks for #91, this looks quite promising, however, I find that now HA complains like so:

```
home-assistant  | 2025-06-26 17:01:35.033 ERROR (MainThread) [custom_components.azure_openai_conversation] Error talking to Azure OpenAI: Error code: 404 - {'error': {'message': 'Invalid URL (POST /v1/responses)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

A quick copilot search suggests that AzureOpenAI should be used as follows:

![Image](https://github.com/user-attachments/assets/425bb1bd-26cf-4b72-b1e6-bef30bc40ccc)

but the current code uses 

```python
    client = openai.AsyncAzureOpenAI(
        azure_endpoint=entry.data[CONF_API_BASE],
        api_version=entry.data[CONF_API_VERSION],
        api_key=entry.data[CONF_API_KEY],
        http_client=get_async_client(hass),
    )
```

and

```python
response: Response = await client.responses.create(**model_args)
```

could this be the issue?

**Comment by bullmastiffo** [comment]
Hi @temporaer, thanks for your message, that's due to API version that you use is older than 2025-03-01. I would recommend to update to 3.1.0 as it doesn't depend on this version in config anymore. 

Also make sure that in Azure you use some of latest models like 4o-mini or 4.1-mini that support responses API.

**Comment by temporaer** [comment]
Hmm, I'm using

```yaml
{
    "created_at": "2025-06-26T14:32:27.326636+00:00",
    "data": {
        "api_base": "https://[...].cognitiveservices.azure.com",
        "api_key": "[...]",
        "api_version": "2025-03-01-preview"
    },
    "disabled_by": null,
    "discovery_keys": {},
    "domain": "azure_openai_conversation",
    "entry_id": "[...]",
    "minor_version": 1,
    "modified_at": "2025-06-26T14:55:51.973781+00:00",
    "options": {
        "chat_model": "gpt-4o-mini",
        "llm_hass_api": [
            "assist"
        ],
        "max_tokens": 500,
        "prompt": "[...]",
        "reasoning_effort": "low",
        "recommended": false,
        "search_context_size": "medium",
        "temperature": 1.0,
        "top_p": 1.0,
        "user_location": false,
        "web_search": true
    },
    "pref_disable_new_entities": false,
    "pref_disable_polling": false,
    "source": "user",
    "subentries": [],
    "title": "Azure OpenAI Conversation",
    "unique_id": null,
    "version": 1
}

```
