### ISSUE TITLE
azure-open-ha ignore intents configured in conversation or automations

### ISSUE THREAD

**Issue by SchmidSP** [joselcaguilar/azure-openai-ha#94]
HA 2025.6.3
azure-open-ha 3.1

**Intents cfg:**
```
conversation:
  intents:
    WerImHof:
      - "Wer steht im Hof?"
      - "Wer ist im Hof?"
      - "Ist jemand im Hof?"
      - "Gibt es jemanden im Hof?"

intent_script:
  WerImHof:
    speech:
      text: "Ich prüfe, wer im Hof ist."
    action:
      - service: automation.trigger
        data:
          entity_id: automation.llm_was_siehst_du_im_hof
```

**Action: (executed via dev console - actions, rest api or automation)**
```
action: conversation.process
data:
  language: de
  text: Wer steht im Hof?
  agent_id: conversation.azure_openai_conversation
```

**Answer with Azure-openai-ha: (wrong intents / automation)**
```
response:
  speech:
    plain:
      speech: >-
        Im Hof ist derzeit niemand. Es gibt keine Bewegung oder Anwesenheit
        erkannt.
      extra_data: null
  card: {}
  language: de
  response_type: action_done
  data:
    targets: []
    success: []
    failed: []
conversation_id: ***
continue_conversation: false
```

**If I use agent_id: conversation.home_assistant (use intents / automation)** 
Answer correct:
```
response:
  speech:
    plain:
      speech: Ich kann keine Person oder ein Tier in diesem Bild erkennen.
      extra_data: null
  card: {}
  language: de
  response_type: action_done
  data:
    targets: []
    success: []
    failed: []
conversation_id: ***
continue_conversation: false
```

intents sentences where not executed with Azure-openai-ha
Seems that azure-openai-h reacts different when called via conversation.process or via voice / text chat over lovelace frontend

Manual HA says 
[Conversation - Home Assistant](https://www.home-assistant.io/integrations/conversation/)
Quote:
" The Conversation integration allows you to converse with Home Assistant. You can either converse by pressing the microphone in the frontend (supported browsers only (no iOS)) or by calling the conversation/process action with the transcribed text."

So in my opinion Azure-openai-ha with conversation.process should execute the automation or intents.
